name: Build Image Debian based

on:
  workflow_dispatch:
    inputs:
      apply:
        type: boolean
        description: "Clean images"
        default: false

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

env:
  REPOSITORY: ${{ vars.IMAGE_NAME }}
  IMAGETAG: ${{ github.ref_name }}-${{ github.run_number }}

run-name: Build Image -> ${{ github.ref_name }}-${{ github.run_number }}

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    environment:
      name: BUILD

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: build image
      run: |
        docker build -t ghcr.io/johnsmall02/${{ env.REPOSITORY }}:${{ env.IMAGETAG }} --no-cache --progress=plain ./foreman

    - name: Show images
      run: |
        docker images

    - name: push image
      run: |
        docker push ghcr.io/johnsmall02/${{ env.REPOSITORY }}:${{ env.IMAGETAG }}
